Ext.define('App.model.GroupGridModel', {
    extend:'Ext.data.Model',
    fields:[
        {name:'id'},
        {name:'nagid'},
        {name:'groupid'},
        {name:'groupname'},
        {name:'typeid'},
        {name:'hourall'},
        {name:'hourfact'},
        {name:'subgroup'},
        {name:'teacherid'},
        {name:'roomid'},
        {name:'stream'},
        {name:'jointdivision'},
        {name:'jointbegin'},
        {name:'jointend'}
    ]
});
