Ext.define('App.model.StreamGridModel', {
    extend:'Ext.data.Model',
    fields:[
     /*   {
            name:'id',
            mapping:'STREAM'
        },*/

        {
            name:'stream',
            mapping:'STREAM'
        },
        {
            name:'typeId',
            mapping:'TYPEID'
        },
        {
            name:'subjectId',
            mapping:'SUBJECTID'
        },
        {
            name:'groupId',
            mapping:'GROUPID'
        },
        {
            name:'nagId',
            mapping:'NAGID'
        },
        {
            name:'raspredId',
            mapping:'RASPREDID'
        },
        {
            name:'teacherId',
            mapping:'TEACHERID'
        },
        {
            name:'roomId',
            mapping:'ROOMID'
        },
        {
            name:'tso',
            mapping:'TSO'
        },
        {
            name:'build',
            mapping:'BUILD'
        },
        {
            name:'level',
            mapping:'LEVEL'
        },
        {
            name:'deleted_nagid',
            mapping:'DELETED_NAGID'
        }
    ]/*,
    idProperty:'id'*/
    //,idgen:'sequential'
});